# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2785996a236e4d4102102dedefd027cf7caa4a57fca6107ef438390d2abd7c10c7841112e4ffc6353a7816206f9726183c156e86e6d5d6880a5d13aa937270f9

test:
  secret_key_base: 4fcf28b8712f31ffdec05ef08e0e7b903f3b90a45261c21cc724c8194798152c233802d78103a6916dfd006f2e903e76bed7aae43675fa57f3999b10e236e9ac

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
