module ApplicationHelper
  # Methods added to this helper will be available to all templates in the application.
  
  Btn_width = '150'
  # Btn_server = 'http://buttons.purplecomet.org'
  # Btn_server = 'http://www.purplecomet.org'
  Btn_server = ''

  def vert_txt(mytext)
    # TODO: remove this
  	mylist = mytext.split(//)
	mytext = mylist.join('<br />')
	return '<div style="margin: 10px; line-height: 0.9em; text-align: center">' + mytext + '</div>'
  end

  def reset_tag(label)
    return "<input type=\"reset\" value=\"#{label}\" />"
  end
  
  def states_array()
    return [ ['--',''] ].concat(
             us_states()).concat([["--",""]]).concat(
             us_territories).concat([["--",""]]).concat(
             canada_provinces)
  end
  
  def country_array()
    return [ ['-- Please select a Country --',''],
             "United States",
             "Afghanistan",
             "Albania",
             "Algeria",
             "Andorra",
             "Angola",
             "Antigua and Barbuda",
             "Argentina",
             "Armenia",
             "Australia",
             "Austria",
             "Azerbaijan",
             "Bahamas",
             "Bahrain",
             "Bangladesh",
             "Barbados",
             "Belarus",
             "Belgium",
             "Belize",
             "Benin",
             "Bhutan",
             "Bolivia",
             "Bosnia and Herzegovina",
             "Botswana",
             "Brazil",
             "Brunei",
             "Bulgaria",
             "Burkina Faso",
             "Burundi",
             "Cambodia",
             "Cameroon",
             "Canada",
             "Cape Verde",
             "Central African Republic",
             "Chad",
             "Chile",
             "China",
             "Colombia",
             "Comoros",
             "Congo, DR",
             "Congo",
             "Costa Rica",
             "Cote D'Ivoire",
             "Croatia",
             "Cuba",
             "Cyprus",
             "Czech Republic",
             "Denmark",
             "Djibouti",
             "Dominica",
             "Dominican Rupublic",
             "Ecuador",
             "Egypt",
             "El Salvador",
             "Equatorial Guinea",
             "Eritrea",
             "Estonia",
             "Ethiopia",
             "Fiji",
             "Finland",
             "France",
             "Gabon",
             "Gambia",
             "Georgia",
             "Germany",
             "Ghana",
             "Greece",
             "Grenada",
             "Guatemala",
             "Guinea",
             "Guinea-Bissau",
             "Guyana",
             "Haiti",
             "Honduras",
             "Hong Kong",
             "Hungary",
             "Iceland",
             "India",
             "Indonesia",
             "Iran",
             "Iraq",
             "Ireland",
             "Israel",
             "Italy",
             "Jamaica",
             "Japan",
             "Jordan",
             "Kazakhstan",
             "Kenya",
             "Kiribati",
             "Kuwait",
             "Kyrgyzstan",
             "Laos",
             "Latvia",
             "Lebanon",
             "Lesotho",
             "Libya",
             "Liechtenstein",
             "Lithuania",
             "Luxembourg",
             "Macau",
             "Macedonia, Republic of",
             "Madagascar",
             "Malawi",
             "Malaysia",
             "Maldives",
             "Mali",
             "Malta",
             "Marshall Islands",
             "Mauritania",
             "Mauritius",
             "Mexico",
             "Micronesia",
             "Moldova",
             "Monaco",
             "Mongolia",
             "Montenegro",
             "Morocco",
             "Mozambique",
             "Myanamar",
             "Namibia",
             "Nauru",
             "Nepal",
             "Netherlands",
             "New Zealand",
             "Nicaragua",
             "Niger",
             "Nigeria",
             "North Korea",
             "Norway",
             "Oman",
             "Pakistan",
             "Palau",
             "Panama",
             "Papua New Guinea",
             "Paraguay",
             "Peru",
             "Philippines",
             "Poland",
             "Portugal",
             "Qatar",
             "Romania",
             "Russia",
             "Rowanda",
             "Saint Kitts and Nevis",
             "Saint Lucia",
             "Saint Vincent and the Grenadines",
             "Samoa",
             "San Marino",
             "Sao Tome and Principe",
             "Saudi Arabia",
             "Senegal",
             "Serbia",
             "Seychelles",
             "Sierra Leone",
             "Singapore",
             "Slovakia",
             "Slovenia",
             "Solomon Islands",
             "Somalia",
             "South Africa",
             "South Korea",
             "Spain",
             "Sri Lanka",
             "Sudan",
             "Suriname",
             "Swaziland",
             "Sweden",
             "Switzerland",
             "Syria",
             "Tajikistan",
             "Taiwan",
             "Tanzania",
             "Thailand",
             "Timor-Leste",
             "Togo",
             "Tonga",
             "Trinidad and Tobago",
             "Tunisia",
             "Turkey",
             "Turkmenistan",
             "Tuvalu",
             "Uganda",
             "Ukraine",
             "United Arab Emirates",
             "United Kingdom",
             "Uruguay",
             "Uzbekistan",
             "Vanuatu",
             "Venezuela",
             "Vietnam",
             "Yemen",
             "Zambia",
             "Zimbabwe",
             "Other"]  
  end

  def grade_array(mygrade)
    return [ ['6th or earlier','6'],['7th','7'],['8th','8'],['9th','9'],['10th','10'],['11th','11'],['12th','12'],['above 12th','13']] 
  end
  
  def select_grade(index,grade)
    result = '<select id="participants_'+ index+ '_grade" name="participants['+index+'][grade]">'
    [ ['6th or earlier','6'],['7th','7'],['8th','8'],['9th','9'],['10th','10'],['11th','11'],['12th','12'],['above 12th','13']].each do |item|
      result += '<option value="'+item[1]+'"'
      if grade == item[1] then
        result += ' selected="selected"'
      end
      result += ">#{item[0]}</option>"
    end
    result += '</select>'
    return result
  end
end
